[package]
name = "qp"
version = "0.1.0"
edition = "2024"
default-run = "acoqp"

[dependencies]
anyhow.workspace = true
clap = { version = "4.6.1", features = ["derive"] }
config = { version = "0.1.0", path = "../config" }
env_logger = "0.11.10"
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_crseo.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-systems_agws.workspace = true
interface.workspace = true
serde-pickle.workspace = true
tokio = { workspace = true, features = ["full"] }
gmt_dos-clients_optics-state = { workspace = true, features = [
  "gmt_dos-clients_arrow",
] }
nanorand = { version = "0.8.0", optional = true }
gmt_dos-clients_scope = { git = "https://github.com/rconan/dos-actors.git", branch = "gmt-ns-im", version = "3.1.0", features = [
  "server",
]  }
faer = "0.24.0"
thiserror = "2.0.18"

[[bin]]
name = "acoqp"
path = "src/bin/main.rs"
required-features = ["acoqp"]

[[bin]]
name = "calibration"
path = "src/bin/calibration.rs"
required-features = ["gmt_dos-systems_agws/shk48"]

[[bin]]
name = "sh24"
path = "src/bin/sh24.rs"
required-features = ["gmt_dos-systems_agws/shk24","interface/serde-pickle"]

[[bin]]
name = "sh24_iir"
path = "src/bin/sh24_iir.rs"
required-features = ["gmt_dos-systems_agws/shk24","interface/serde-pickle"]

[features]
acoqp = ["gmt_dos-systems_agws/shk48", "nanorand"]
nanorand = ["dep:nanorand"]
